name: CD

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**/README.md'
      - '**/blob/*'
  pull_request:
    branches: [ master ]

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        source-url: https://nuget.pkg.github.com/AaksPowerPointParser/index.json
      env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_KEY}}
    - name: Restore Dependencies
      run: dotnet restore ./PowerPointParser
    - name: Build 
      run: dotnet build ./PowerPointParser --configuration Release --no-restore
    - name: Publish to Nuget
      run: dotnet nuget push ./PowerPointParser/PowerPointParser/bin/Release/*.nupkg
