name: CD

on:  
  push:
    tags:
      - 'v*.*.*.*'

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
        source-url: https://nuget.pkg.github.com/AaksPowerPointParser/index.json
      env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Restore Dependencies
      run: dotnet restore ./PowerPointParser
    - name: Build 
      run: dotnet build ./PowerPointParser --no-restore
    - name: Test 
      run: dotnet test ./PowerPointParser --no-build --verbosity normal
    - name: Push to Nuget
      run: dotnet nuget push ./PowerPointParser/out/*.nupkg --skip-duplicate --no-symbols true