name: CD

on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9].*"

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore Dependencies
      run: dotnet restore ./PowerPointParser
    - name: Build 
      run: dotnet build ./PowerPointParser --configuration Release --no-restore
    - name: Set Version from Tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
    - name: Pack
      run: dotnet pack ./PowerPointParser/PowerPointParser/PowerPointParser.csproj --configuration Release --output .
    - name: Push
      run: dotnet nuget push AaksPowerPointParser.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${GITHUB_TOKEN}
      env:
        GITHUB_TOKEN: ${{ secrets.NUGET_KEY }}
