name: CD

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**/README.md'
      - '**/blob/*'

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore Dependencies
      run: dotnet restore ./PowerPointParser
    - name: Build 
      run: dotnet build ./PowerPointParser --configuration Release --no-restore
    - name: Publish to Nuget
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
        PROJECT_FILE_PATH: ./PowerPointParser/PowerPointParser.csproj
        NUGET_KEY: ${{ secrets.NUGET_KEY }}
      
