name: CI

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**/README.md'
      - '**/blob/*'
  pull_request:
    branches: [ master ]
  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ./PowerPointParser
    - name: Build 
      run: dotnet build ./PowerPointParser --no-restore
    - name: Test 
      run: dotnet test ./PowerPointParser --no-build --verbosity normal
    - name: Test Reporting
      uses: zyborg/dotnet-tests-report@v1.4.4
      with:
        project_path: ./PowerPointParser/PowerPointParserTests
        report_name: project_unit_tests
        report_title: Unit Tests
        github_token: ${{ secrets.GITHUB_TOKEN }}
        gist_name: power_point_parser_tests.md
        gist_badge_label: 'Tests: %Counters_passed%/%Counters_total%'
        gist_token: ${{ secrets.GIST_TOKEN }}


    
